openapi: 3.0.0
info:
  title: SimilarProducts
  version: '1.0'
servers:
  - url: 'http://localhost:5000'
paths:
  '/product/{productId}/similar':
    parameters:
      - schema:
          type: string
        name: productId
        in: path
        required: true
    get:
      operationId: get-product-similar
      summary: Similar products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: List of similar products to a given one ordered by similarity
                minItems: 0
                uniqueItems: true
                items:
                  $ref: '#/components/schemas/Product'
        '503':
          description: Service Temporarily Unavailable. See the 'Retry-After' header with the recommended number of seconds to try again
components:
  schemas:
    Product:
      title: Product
      type: object
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        price:
          type: number
        availability:
          type: boolean
      description: Information about Product
